### PR TITLE
Replace plexus-component-metadata plugin (deprecated) with Sisu

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Do all plexus project use JSR-330 components instead plexus-annotatnios? 
Maybe in first step add sisu and add enforcer rule with warning that project use plexus-annotation

**Comment by slachiewicz** [comment]
I don't think so,. But with parent upgrade in subprojects we can add explicitly version

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slachiewicz** [comment]
> Do all plexus project use JSR-330 components instead plexus-annotatnios? Maybe in first step add sisu and add enforcer rule with warning that project use plexus-annotation

https://github.com/apache/maven/blob/maven-3.9.x/maven-core/src/main/java/org/apache/maven/DefaultMaven.java#L66

and still everything in maven-compat use Plexus annotations - and agreed to not touch it

**Comment by slachiewicz** [comment]
I'll wait with this change until next pom release

**Pull request merged**
